### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Vaishnvi** [javierlorenzod/CAPformer#1]
Hi @javierlorenzod,

Thanks for your great work! Can you please let me know when will be the code released?

Regards,
Vaishnavi

**Comment by javierlorenzod** [comment]
> Hi @javierlorenzod,
> 
> Thanks for your great work! Can you please let me know when will be the code released?
> 
> Regards,
> Vaishnavi

Hi @Vaishnvi,

Thank you for your interest in my work! I have been busy these last months since the paper release, I will notify you whenever I release it.

**Comment by javierlorenzod** [comment]
Hi @Vaishnvi , the initial code used has been released. However, I will not support it for now, due to lack of time. It is mostly based on the code in https://github.com/ykotseruba/PedestrianActionBenchmark for keeping a consistency in evaluation.

Hope it helps you!
